title: Michał Strzeżoń
description: Software Engineer with AI/ML knowledge, passionate about aviation analytics and intelligent software solutions.

# Social links
github_username: mstrzezon
email: michal.m.strzezon@gmail.com

# SEO
author: Michał Strzeżoń
keywords: software engineer, data analytics, aviation analytics, python developer, AGH graduate
url: "https://mstrzezon.github.io"
baseurl: ""

# Analytics (optional)
google_analytics: # Add your GA tracking ID if you want

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Theme override - using custom layout
theme: 

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
